version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_service
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch_service
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ES_PORT:-9200}:9200"
    volumes:
      - es_storage:/usr/share/elasticsearch/data
    restart: always

volumes:
  qdrant_storage:
  es_storage: